on:
  push:
    branches:
      - master
  pull_request:
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3.5.0
      with:
        go-version: 1.19.x

    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Cache Go dependencies
      uses: actions/cache@v3.2.4
      with:
        path: |
          ~/go/pkg/mod              # Module download cache
          ~/.cache/go-build         # Build cache (Linux)
          ~/Library/Caches/go-build # Build cache (Mac)
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      # Temporarily disable the race detector until
      # https://github.com/tidwall/redcon/pull/62
      # run: go test -race ./...
      run: go test ./...
